// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RideManagement.Context;

#nullable disable

namespace RideManagement.Migrations
{
    [DbContext(typeof(RideDbContext))]
    partial class RideDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RideManagement.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<int>("BookedOn")
                        .HasColumnType("int");

                    b.Property<int>("NoOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RideSchedulesID")
                        .HasColumnType("int");

                    b.Property<int>("RiderUserId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RideManagement.Models.Distance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DistanceInKMS")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Distances");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DistanceInKMS = 500,
                            From = "Kolkata",
                            To = "Chennai"
                        },
                        new
                        {
                            ID = 2,
                            DistanceInKMS = 200,
                            From = "Delhi",
                            To = "Pune"
                        },
                        new
                        {
                            ID = 3,
                            DistanceInKMS = 300,
                            From = "Kolkata",
                            To = "Bangalore"
                        });
                });

            modelBuilder.Entity("RideManagement.Models.RideSchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MotoristUserId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfSeatsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("RideFare")
                        .HasColumnType("int");

                    b.Property<string>("RideFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RideStartsOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RideTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RideTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleRegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RideSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
